#!/bin/bash

# function test {
#   docker compose -f docker-compose.yml exec -e "MIX_ENV=test" app mix test
# }
function init {
  docker compose -f docker-compose.yml build
  docker compose run app mix ecto.reset
  docker compose up
}

function test {
  docker compose exec -e "MIX_ENV=test" app mix test
}

function reset {
    echo "Resetting the database"
    docker compose run app mix ecto.reset
}

function deps.get {
    docker compose run app mix deps.get
}

function help {
  printf "%s <task>\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"