#!/bin/bash

function reset {
    echo "Resetting the database"
    docker compose run app mix ecto.reset
}

function help {
  printf "%s <task>\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"